### ISSUE TITLE
change the name to Ed 

### ISSUE THREAD

**Issue by ryan1234565** [SlimShadyIAm/gir#31]

**Comment by ja1dan** [comment]
Change this ratio

**Comment by NSAntoine** [comment]
are you guys gonna keep doing this for every gir name change

**Comment by ja1dan** [comment]
I'm gonna keep closing them until she (or whoever is sending these) stops because they're unfunny and useless.

**Comment by NSAntoine** [comment]
I can assure you I'm not making accounts with my deadname LMFAO
